import Vue from 'vue';
import AvatarInfo from '../components/AvatarInfo.vue';
import CountdownTimer from '../components/CountdownTimer.vue';
import SafeDialog from '../components/dialogs/SafeDialog.vue';
import DisplayName from '../components/DisplayName.vue';
import InstanceInfo from '../components/InstanceInfo.vue';
import InviteYourself from '../components/InviteYourself.vue';
import LastJoin from '../components/LastJoin.vue';
import Launch from '../components/Launch.vue';
import Location from '../components/Location.vue';
import LocationWorld from '../components/LocationWorld.vue';
import SimpleSwitch from '../components/SimpleSwitch.vue';
import Timer from '../components/Timer.vue';

Vue.component('SafeDialog', SafeDialog);
Vue.component('SimpleSwitch', SimpleSwitch);
Vue.component('Location', Location);
Vue.component('Timer', Timer);
Vue.component('InstanceInfo', InstanceInfo);
Vue.component('LastJoin', LastJoin);
Vue.component('CountdownTimer', CountdownTimer);
Vue.component('AvatarInfo', AvatarInfo);
Vue.component('DisplayName', DisplayName);
Vue.component('InviteYourself', InviteYourself);
Vue.component('Launch', Launch);
Vue.component('LocationWorld', LocationWorld);
