const photonEmojis = [
    'Angry',
    'Blushing',
    'Crying',
    'Frown',
    'Hand Wave',
    'Hang Ten',
    'In Love',
    'Jack O Lantern',
    'Kiss',
    'Laugh',
    'Skull',
    'Smile',
    'Spooky Ghost',
    'Stoic',
    'Sunglasses',
    'Thinking',
    'Thumbs Down',
    'Thumbs Up',
    'Tongue Out',
    'Wow',
    'Arrow Point',
    "Can't see",
    'Hourglass',
    'Keyboard',
    'No Headphones',
    'No Mic',
    'Portal',
    'Shush',
    'Bats',
    'Cloud',
    'Fire',
    'Snow Fall',
    'Snowball',
    'Splash',
    'Web',
    'Beer',
    'Candy',
    'Candy Cane',
    'Candy Corn',
    'Champagne',
    'Drink',
    'Gingerbread',
    'Ice Cream',
    'Pineapple',
    'Pizza',
    'Tomato',
    'Beachball',
    'Coal',
    'Confetti',
    'Gift',
    'Gifts',
    'Life Ring',
    'Mistletoe',
    'Money',
    'Neon Shades',
    'Sun Lotion',
    'Boo',
    'Broken Heart',
    'Exclamation',
    'Go',
    'Heart',
    'Music Note',
    'Question',
    'Stop',
    'Zzz'
];

const photonEventType = [
    'MeshVisibility',
    'AnimationFloat',
    'AnimationBool',
    'AnimationTrigger',
    'AudioTrigger',
    'PlayAnimation',
    'SendMessage',
    'SetParticlePlaying',
    'TeleportPlayer',
    'RunConsoleCommand',
    'SetGameObjectActive',
    'SetWebPanelURI',
    'SetWebPanelVolume',
    'SpawnObject',
    'SendRPC',
    'ActivateCustomTrigger',
    'DestroyObject',
    'SetLayer',
    'SetMaterial',
    'AddHealth',
    'AddDamage',
    'SetComponentActive',
    'AnimationInt',
    'AnimationIntAdd',
    'AnimationIntSubtract',
    'AnimationIntMultiply',
    'AnimationIntDivide',
    'AddVelocity',
    'SetVelocity',
    'AddAngularVelocity',
    'SetAngularVelocity',
    'AddForce',
    'SetUIText',
    'CallUdonMethod'
];

const photonEventTableTypeFilterList = [
    'Event',
    'OnPlayerJoined',
    'OnPlayerLeft',
    'ChangeAvatar',
    'ChangeStatus',
    'ChangeGroup',
    'PortalSpawn',
    'DeletedPortal',
    'ChatBoxMessage',
    'Moderation',
    'Camera',
    'SpawnEmoji',
    'MasterMigrate'
];

export { photonEmojis, photonEventType, photonEventTableTypeFilterList };
