<Project>
  <PropertyGroup>
    <!-- Set each project to have a separate folder under obj\ and bin\ -->
    <BaseIntermediateOutputPath>obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <BaseOutputPath>bin\$(MSBuildProjectName)\</BaseOutputPath>
  </PropertyGroup>

  <PropertyGroup>
    <IsWindows>$([MSBuild]::IsOsPlatform('Windows'))</IsWindows>
    <IsLinux>$([MSBuild]::IsOsPlatform('Linux'))</IsLinux>
    <IsOSX>$([MSBuild]::IsOsPlatform('OSX'))</IsOSX>
  </PropertyGroup>

  <!-- Platform-specific Runtime Identifiers -->
  <PropertyGroup Condition="$(IsWindows) and '$(Platform)'=='x64'">
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
  <PropertyGroup Condition="$(IsWindows) and '$(Platform)'=='ARM64'">
    <PlatformTarget>ARM64</PlatformTarget>
    <RuntimeIdentifier>win-arm64</RuntimeIdentifier>
  </PropertyGroup>
  <PropertyGroup Condition="$(IsLinux) and '$(Platform)' == 'x64'">
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
  </PropertyGroup>
  <PropertyGroup Condition="$(IsLinux) and '$(Platform)'=='ARM64'">
    <PlatformTarget>ARM64</PlatformTarget>
    <RuntimeIdentifier>linux-arm64</RuntimeIdentifier>
  </PropertyGroup>
  <PropertyGroup Condition="$(IsOSX) and '$(Platform)' == 'x64'">
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>osx-x64</RuntimeIdentifier>
  </PropertyGroup>
  <PropertyGroup Condition="$(IsOSX) and '$(Platform)'=='ARM64'">
    <PlatformTarget>ARM64</PlatformTarget>
    <RuntimeIdentifier>osx-arm64</RuntimeIdentifier>
  </PropertyGroup>
</Project>
