name: VRCX Build macOS

on:
    workflow_dispatch:

concurrency:
    group: build-macos-${{ github.ref }}
    cancel-in-progress: true

permissions:
    contents: write

jobs:
    set_version:
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.version.outputs.version }}
            date: ${{ steps.version.outputs.date }}
        steps:
            - uses: actions/checkout@v5
            - id: version
              run: |
                  export FILENAME="$(cat Version)"
                  export DATE="$(cat Version)"
                  echo "version=${FILENAME}" >> $GITHUB_OUTPUT
                  echo "date=${DATE}" >> $GITHUB_OUTPUT

    build_electron_html:
        runs-on: ubuntu-latest
        needs: set_version
        steps:
            - uses: actions/checkout@v5
            - name: Set version
              run: echo "${{ needs.set_version.outputs.version }}" > Version
            - uses: actions/setup-node@v6
              with:
                  node-version: lts/*
            - name: Get npm cache directory
              id: npm-cache-dir
              run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
            - uses: actions/cache@v5
              with:
                  path: ${{ steps.npm-cache-dir.outputs.dir }}
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: ${{ runner.os }}-node-
            - name: Restore dependencies
              run: npm ci
            - name: Build Electron html
              env:
                  SENTRY_AUTH_TOKEN: ${{ secrets.SentryAuthToken }}
              run: npm run prod-linux
            - name: Upload Electron-html artifacts
              uses: actions/upload-artifact@v7
              with:
                  name: Electron-html
                  path: build/html

    build_dotnet_macos:
        runs-on: macos-latest
        needs: set_version
        strategy:
            matrix:
                include:
                    - arch: x64
                      project: VRCX-Electron.csproj
                      artifact: Electron-Release-macOS-x64
                    - arch: arm64
                      project: VRCX-Electron-arm64.csproj
                      artifact: Electron-Release-macOS-arm64
        steps:
            - uses: actions/checkout@v5
            - name: Setup .NET 9
              uses: actions/setup-dotnet@v5
              with:
                  dotnet-version: '9.0.x'
            - name: Set version
              run: echo "${{ needs.set_version.outputs.version }}" > Version
            - uses: actions/cache@v5
              with:
                  path: ~/.nuget/packages
                  key: ${{ runner.os }}-nuget-${{ matrix.arch }}-${{ hashFiles(format('**/Dotnet/{0}', matrix.project)) }}
                  restore-keys: ${{ runner.os }}-nuget-
            - name: Build Electron ${{ matrix.arch }} .NET Application
              run: dotnet build 'Dotnet/${{ matrix.project }}' -p:Configuration=Release -p:WarningLevel=0 -p:Platform=${{ matrix.arch }} -p:PlatformTarget=${{ matrix.arch }} -p:RestorePackagesConfig=true -t:"Restore;Clean;Build" -m -a ${{ matrix.arch }}
            - name: Upload Electron ${{ matrix.arch }} dotnet artifacts
              uses: actions/upload-artifact@v7
              with:
                  name: ${{ matrix.artifact }}
                  path: build/Electron

    build_electron_macos:
        runs-on: macos-latest
        needs: [set_version, build_dotnet_macos, build_electron_html]
        steps:
            - uses: actions/checkout@v5
            - name: Set version
              run: echo "${{ needs.set_version.outputs.version }}" > Version
            - uses: actions/setup-node@v6
              with:
                  node-version: lts/*
            - name: Get npm cache directory
              id: npm-cache-dir
              run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
            - uses: actions/cache@v5
              with:
                  path: ${{ steps.npm-cache-dir.outputs.dir }}
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: ${{ runner.os }}-node-
            - name: Restore dependencies
              run: npm ci
            - name: Download Electron html artifacts
              uses: actions/download-artifact@v8
              with:
                  name: Electron-html
                  path: build/html
            - name: Download x64 Electron dotnet artifacts
              uses: actions/download-artifact@v8
              with:
                  name: Electron-Release-macOS-x64
                  path: build/Electron
            - name: Build x64 macOS .dmg
              run: npm run build-electron
            - name: Upload x64 Electron macOS artifacts
              uses: actions/upload-artifact@v7
              with:
                  name: Electron-MacDmg-x64
                  path: 'build/VRCX_${{ needs.set_version.outputs.version }}_x64.dmg'
            - name: Cleanup
              run: rm -R build/Electron
            - name: Download arm64 Electron dotnet artifacts
              uses: actions/download-artifact@v8
              with:
                  name: Electron-Release-macOS-arm64
                  path: build/Electron
            - name: Build arm64 macOS .dmg
              run: npm run build-electron-arm64
            - name: Upload arm64 Electron macOS artifacts
              uses: actions/upload-artifact@v7
              with:
                  name: Electron-MacDmg-arm64
                  path: 'build/VRCX_${{ needs.set_version.outputs.version }}_arm64.dmg'
