name: CI
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint_js:
    name: Lint JS (Oxlint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: oxc-project/oxlint-action@v2.0.1
        with:
          config: .oxlintrc.json
        continue-on-error: true

  format_js:
    name: Format JS (Oxfmt)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: npm
      - run: npm install --frozen-lockfile
      - run: npm run fmt:check

  lint_c_sharp_windows:
    name: Lint ${{ matrix.project }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        project: [Dotnet/VRCX-Cef.csproj]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Annotate
        uses: JetBrains/ReSharper-InspectCode@v0.11
        with:
          solution: ${{ matrix.project }}
        continue-on-error: true

  lint_c_sharp_linux:
    name: Lint ${{ matrix.project }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          [Dotnet/VRCX-Electron.csproj, Dotnet/VRCX-Electron-arm64.csproj]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Annotate
        uses: JetBrains/ReSharper-InspectCode@v0.11
        with:
          solution: ${{ matrix.project }}
        continue-on-error: true

  format_c_sharp:
    name: Format C# (CSharpier)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup .NET 9
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'
      - name: Run CSharpier
        run: |
          dotnet tool restore
          dotnet csharpier check .
